apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ey-sample-repo-01
  description: Sample Repository
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:default/teama
  lifecycle: experimental
